name: "Release new version"
on:
  push:
    tags:
      - "**"
jobs:
  setup_env:
    runs-on: ubuntu-latest
    outputs:
      DEBUG_MODE: ${{ steps.build_mode.DEBUG_MODE }}
    steps:
      - name: build_mode
        if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '-dev')
        run: echo "IS-DEV" && echo "DEBUG_MODE=ON" >> "$GITHUB_OUTPUT"

  build1:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - name: Configure
        env:
          DEBUG_MODE: ${{needs.setup_env.outputs.DEBUG_MODE}}
        run: echo "PRESET = $PRESET - DEBUG_MODE = $DEBUG_MODE"
